# Generated by Django 4.2.24 on 2025-09-20 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post title', max_length=200)),
                ('slug', models.SlugField(help_text='URL friendly verbose of title', max_length=255, unique=True)),
                ('body', models.TextField(help_text='Post content')),
                ('excerpt', models.CharField(blank=True, help_text='Short description of the post', max_length=300)),
                ('featurd_image', models.URLField(blank=True, help_text='Featured image url')),
                ('is_published', models.BooleanField(default=True, help_text='Wheater this post is publicly visible ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='The user who created the post', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='postapi_pos_created_127ad2_idx'), models.Index(fields=['is_published'], name='postapi_pos_is_publ_b75df3_idx'), models.Index(fields=['author'], name='postapi_pos_author__578378_idx')],
            },
        ),
    ]
