# Generated by Django 4.2.24 on 2025-09-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='featurd_image',
            new_name='featured_image',
        ),
    ]
